# Generated by Django 3.0.6 on 2020-05-27 14:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvData',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('4f33e022-9e9e-4dd4-be74-ce3891e3c51e'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('csv_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
