version: "3"

services:
  db:
   image: postgres:9.6.5
   volumes:
     - psql-data:/var/lib/postgresql/data
     - .:/application
   ports:
     - "9432:5432"
  web:
    build: .
    working_dir: /application/server
    env_file:
      - server/config/.env
    command: "tail -f /dev/null"
    # command:
    #   ["bash", "docker_entry.sh", "python3", "manage.py", "runserver", "0:8000"]
    volumes:
      - .:/application
      - app-python-site-packages:/usr/local/lib/python3.6/site-packages
      - app-usr-local-bin:/usr/local/bin
    ports:
      - "9090:8000"

volumes:
  app-python-site-packages:
    driver: local
  app-usr-local-bin:
    driver: local
  psql-data:
    driver: local
